### ISSUE TITLE
AttributeError: module 'ogr' has no attribute 'GetDriverByName' when running "build_semantic_segmentation_training_data"

### ISSUE THREAD

**Issue by cameronbronstein** [pgbrodrick/ecoCNN#1]
Hi there,

I'm working through the CNN_tutorial. After having a heck of a time getting gdal installed on my computer (my own issue, of course), I seem to have it set up right in a conda environment with all of the listed dependencies installed.  When I open Jupyter in the environment, all the libraries load and I can run their methods on their own. However, when trying to run `build_semantic_segmentation_training_data`, I get an attribute error saying that `ogr has no attribute GetDriverByName`. This points to the `build_training_data.py` module and the `get_proj` function. 

I am able to call `ogr.GetDriverByName` on its own in a separate Jupyter cell, so I am at my wits end on how to troubleshoot this error since the module clearly contains the specified method. My only guess is that perhaps it's a version issue/ mismatch between the library and my conda env?

Here is the output:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-83bbd167fe44> in <module>
     14                                       boundary_file_vector_flag=True,
     15                                       ignore_projections=ignore_projections,
---> 16                                       response_vector_flag=True)
     17 print(features.shape)
     18 print(responses.shape)

~/workspace/ecoCNN/build_training_data.py in build_semantic_segmentation_training_data(window_radius, samples_per_response_per_site, feature_file_list, response_file_list, response_vector_flag, boundary_file_list, boundary_file_vector_flag, boundary_bad_value, internal_window_radius, center_random_offset_fraction, response_repeats, savename, nodata_maximum_fraction, response_minimum_fraction, fill_in_feature_data, global_scale_flag, local_scale_flag, nodata_value, random_seed, n_folds, verbose, ignore_projections)
    261     np.random.seed(random_seed)
    262 
--> 263   check_data_matches(feature_file_list,response_file_list,response_vector_flag,boundary_file_list,boundary_file_vector_flag,ignore_projections)
    264 
    265   if (isinstance(samples_per_response_per_site,list)):

~/workspace/ecoCNN/build_training_data.py in check_data_matches(set_a, set_b, set_b_is_vector, set_c, set_c_is_vector, ignore_projections)
     70     for n in range(0, len(set_a)):
     71       a_proj = get_proj(set_a[n],False)
---> 72       b_proj = get_proj(set_b[n],set_b_is_vector)
     73 
     74       if (a_proj != b_proj and ignore_projections == False):

~/workspace/ecoCNN/build_training_data.py in get_proj(fname, is_vector)
     24   if (is_vector):
     25     if (os.path.basename(fname).split('.')[-1] == 'shp'):
---> 26       vset = ogr.GetDriverByName('ESRI Shapefile').Open(fname,gdal.GA_ReadOnly)
     27     elif (os.path.basename(fname).split('.')[-1] == 'kml'):
     28       vset = ogr.GetDriverByName('KML').Open(fname,gdal.GA_ReadOnly)

AttributeError: module 'ogr' has no attribute 'GetDriverByName'
```

Would be grateful for any ideas on how to fix this! Thanks for your help and for sharing this resource.

**Comment by pgbrodrick** [comment]
Hi @cameronbronstein,

Go ahead and pull and retry...I updated the gdal imports to come from osgeo, which commonly helps.  If not, there's probably still something up with your install.  Sounds like you've been having general trouble there...if you have a conda installation setup, you can use the instructions on our other repo (www.github.com/pgbrodrick/rsCNN) to set up that environment, and it should transfer over hear pretty cleanly.  Let me know either way.

**Comment by cameronbronstein** [comment]
Hi @pgbrodrick,

That update did the trick - thanks so much for the quick reply and fix. I'm sure this will be a helpful reference if I ever run into similar issues with other libraries. And thanks for the rsCNN conda installation link. That also makes things more explicit.

Cheers.
